# Generated by Django 4.1.7 on 2023-04-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("board", models.IntegerField(null=True)),
                ("name", models.CharField(max_length=20)),
                ("pass1", models.CharField(max_length=20)),
                ("gender", models.IntegerField(default=0)),
                ("tel", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=100)),
                ("picture", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("birthday", models.DateTimeField(null=True)),
            ],
        ),
    ]
