# Generated by Django 4.1.7 on 2023-04-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="address",
        ),
        migrations.RemoveField(
            model_name="member",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="member",
            name="board",
        ),
        migrations.AddField(
            model_name="member",
            name="adress",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
