# Generated by Django 4.1.7 on 2023-04-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="address_detail",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
