# Generated by Django 4.1.7 on 2023-04-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0002_member_address_detail"),
        ("member", "0002_remove_member_address_remove_member_birthday_and_more"),
    ]

    operations = []
