# Generated by Django 4.1.7 on 2023-04-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0003_merge_20230411_1144"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="address",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="birthday",
            field=models.DateTimeField(null=True),
        ),
    ]
