# Generated by Django 4.1.7 on 2023-04-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.CharField(max_length=20, null=True)),
                ("subject", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=5000)),
                ("regdate", models.DateTimeField(null=True)),
                ("readcnt", models.IntegerField(default=0)),
                ("file1", models.CharField(max_length=300)),
            ],
        ),
    ]
