# Generated by Django 4.1.7 on 2023-04-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mem_Resume",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("content", models.CharField(max_length=5000, null=True)),
                ("company", models.CharField(max_length=40, null=True)),
                ("job", models.CharField(max_length=40)),
            ],
        ),
    ]
